### ISSUE TITLE
[Eco Pass KIT v2.0.0] Update page-software-development-view.md API diagram

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/eco-pass-kit#15]
# What needs to be done?

- [ ] Update API diagram to match aligned one: https://github.com/eclipse-tractusx/eco-pass-kit/blob/757cde9c178985ab1e1da8d9c832074581a33764/docs/page-software-development-view.md?plain=1#L23-L32
- [ ] Update the External API calls with the correct input of data
- [ ] Explain how does the Digital Product Pass returns data ([Data Retrieval Guide](https://github.com/catenax-ng/tx-digital-product-pass/blob/753f6b62ea3338b44e183af01b4b10351740e966/docs/data%20retrieval%20guide/DataRetrievalGuide.md?plain=1#L111) Based)

**Comment by maxim-bo** [comment]
review done, comments left in #29
