### ISSUE TITLE
[Eco Pass KIT v2.0.0] Add Digital Product Pass 3.0.0

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/eco-pass-kit#16]
# What needs to be done?

- [ ] Add the Digital Product Pass model here:
 https://github.com/eclipse-tractusx/eco-pass-kit/blob/757cde9c178985ab1e1da8d9c832074581a33764/docs/page-adoption-view.md?plain=1#L246C1-L246C1

- [ ] Add explanation about the model

**Comment by maxim-bo** [comment]
@matbmoser review done in #28: just some minor types, overall it looks good to me :)
