### ISSUE TITLE
[Eco Pass KIT v2.0.0] Update business architecture diagram

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/eco-pass-kit#17]
# What needs to be done?

- [x] Add The DPP aspect to the diagram
- [x] Add referers to the "EDC discovery"

**Comment by matbmoser** [comment]
This diagram was added: 
![adoption-view-EcoPassKITBusinessArch](https://github.com/eclipse-tractusx/eco-pass-kit/assets/71728767/ecd5531d-9dec-4496-a6ef-1f763d96cf5f)

**Comment by maxim-bo** [comment]
@matbmoser review done, two minor things noticed, however, overall fine
