### ISSUE TITLE
[Eco Pass KIT v2.0.0] Add operation overview based on the Admin Guide

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/eco-pass-kit#18]
# What needs to be done?

- [ ] Make reference to the standarization from the Triangle from Digital Product Pass
- [ ] Add examples on how to register assets, policies and contracts
- [ ] Add examples on how to register digital twins for transmission, battery and digital product pass
- [ ] Move external API calls table with standards from development to operation view

**Comment by maxim-bo** [comment]
@matbmoser review done in PR for #25
