### ISSUE TITLE
[Eco Pass KIT v2.0.0] Add swagger hub API documentation

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/eco-pass-kit#20]
# What needs to be done?

- [ ] Add the API documentation of the DPP in the software adaption view
- [ ] Upload to swagger hub the API documentation 

## Examples:

- https://github.com/eclipse-tractusx/tractusx-edc/blob/main/.github/workflows/publish-swaggerhub.yaml
- Configuration Secret Alias: https://github.com/eclipse-tractusx/.eclipsefdn/blob/7d029c6de75c23696bf99d9c81ca0b3f47162e80/otterdog/eclipse-tractusx.jsonnet#L53
- https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.6.0-rc1

**Comment by saudkhan116** [comment]
A workflow is implemented to deploy the API Specs to the SwaggerHub. #
Link to the dpp swaggerhub: https://app.swaggerhub.com/apis/eclipse-tractusx-bot/digital-product-pass/1.3.1

**Comment by matbmoser** [comment]
Wonderful! Thank you @saudkhan116 !
