### ISSUE TITLE
Give ChristopherWinter WriteAccess

### ISSUE THREAD

**Issue by efficient0482** [eclipse-tractusx/eco-pass-kit#3]
hello, 

in order to continue our work ChristopherWinter needs write access to The [PCF-KIT(https://github.com/eclipse-tractusx/pcf-exchange-kit) and [Eco-Pass-KIT](https://github.com/eclipse-tractusx/eco-pass-kit). 

Please grant him these rights or give us advice on how to obtain these.

Here is his [profile](https://github.com/ChristopherWinterZF).
He has signed the ECA but we has neither Committer nor Contributer. The [PCF-KIT(https://github.com/eclipse-tractusx/pcf-exchange-kit) and [Eco-Pass-KIT](https://github.com/eclipse-tractusx/eco-pass-kit) are the first he is working on. 
He must be able to approve and manage these repositories

kind Regards

Luis

@Siegfriedk @netomi @danielmiehle

**Comment by netomi** [comment]
The self-service does not handle permissions for individual users. You should direct this to the HelpDesk via https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/new

Granting write access to a non-committer will most likely not be accepted but you should clarify that via the HelpDesk where the relevant people are involved to discuss this.

**Comment by efficient0482** [comment]
Thank You !
