### ISSUE TITLE
[Eco Pass KIT v2.0.0] Update Technical Context Diagram

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/eco-pass-kit#8]
## What needs to be changed?

The context image is outdated and needs to be fixed here:

https://github.com/eclipse-tractusx/eco-pass-kit/blob/bc89fbdaabcf7bd54725e6f20e0b1e8abac86e59/docs/page-software-development-view.md?plain=1#L16

## New Content:

![image](https://github.com/eclipse-tractusx/eco-pass-kit/assets/71728767/9eb89b02-cbf1-473d-ae07-53863631f055)

**Comment by maxim-bo** [comment]
review done, just a minor adjustment of the licensing years needed. other than that fine
